from .custom_backend.organic_search import CustomGoogleScholarOrganic
from .custom_backend.profiles_results import CustomGoogleScholarProfiles
from .custom_backend.author_info_all_articles import CustomGoogleScholarAuthor
from .custom_backend.top_mandates_metrics import CustomGoogleScholarTopMandates
from .custom_backend.top_publications_metrics import CustomGoogleScholarTopPublications
from .custom_backend.top_publications_article import CustomGoogleScholarTopPublicationArticle
from .custom_backend.top_publications_article_citation import CustomGoogleScholarTopPublicationArticleCitation